In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#from zipfile import ZipFile

In [ ]:
'''
with ZipFile("/content/drive/MyDrive/first chunk.zip", 'a') as zipObj:
  zipObj.extractall("/content/drive/MyDrive/Colab Notebooks")
 '''

In [2]:
!pip install trustee --user
!pip install graphviz

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.0/49.0 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.7/328.7 kB 26.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 65.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.3/819.3 kB 50.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.0/138.0 kB 12.9 MB/s eta 0:00:00
  Created wheel for sphinxemoji: filename=sphinxemoji-0.2.0-py3-none-any.whl size=44407 sha256=b823f7f1d2be986d7ce325a856d4db9ab9c5bb817673c30936380a9cab7651cd
  Stored in directory: /root/.cache/pip/wheels/64/a4/96/10ec59245ae6f2b45d4509261572f3d6a0db4a7c00d7a6d4c6
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4832 sha256=316dbabb22ba88df74d018e5cf44c1ea26e13acf4eb32d321f72a2700b201d9b
  Stored in dire

In [1]:
!python drive/MyDrive/Colab\ Notebooks/edited_flowpic_replication/run.py train

Streaming output truncated to the last 5000 lines.
 [1 0 0]]
[[0 1 0]
 [0 1 0]]
[[0 1 0]
 [0 0 1]]
 410/1084 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9953 - loss: 0.0096[[0 1 0]
 [0 0 1]]
[[0 1 0]
 [0 1 0]]
[[0 0 1]
 [0 1 0]]
[[0 0 1]
 [0 0 1]]
[[0 0 1]
 [0 1 0]]
[[0 0 1]
 [0 1 0]]
[[0 1 0]
 [1 0 0]]
[[0 1 0]
 [1 0 0]]
[[1 0 0]
 [0 1 0]]
 419/1084 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9953 - loss: 0.0096[[1 0 0]
 [0 1 0]]
[[0 1 0]
 [1 0 0]]
[[0 1 0]
 [0 1 0]]
[[0 1 0]
 [1 0 0]]
[[1 0 0]
 [1 0 0]]
[[0 0 1]
 [0 0 1]]
 425/1084 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9953 - loss: 0.0096[[0 1 0]
 [0 1 0]]
[[1 0 0]
 [0 0 1]]
[[0 0 1]
 [0 0 1]]
[[1 0 0]
 [0 0 1]]
[[0 0 1]
 [0 1 0]]
[[0 1 0]
 [1 0 0]]
[[0 1 0]
 [1 0 0]]
[[0 1 0]
 [1 0 0]]
 433/1084 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9953 - loss: 0.0096[[1 0 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]]
[[0 0 1]
 [0 1 0]]
[[0 0 1]
 [0 0 1]]
[[0 1 0]
 [0 1 0]]
[[1 0 0]
 [0 1 0]]
[[0 0 1]
 [0 1 0]]
[[0 1 0]
 [1 0 0]]
 441/108

In [2]:
!python drive/MyDrive/Colab\ Notebooks/edited_flowpic_replication/run.py pred

Streaming output truncated to the last 5000 lines.
save done

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                    Classification Trust Report                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                       +-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                       |
|                 

In [ ]:
# Checking the decision tree model created by the trustee
!python drive/MyDrive/Colab\ Notebooks/edited_flowpic_replication/run.py dtpred

2024-09-15 16:43:32.397453: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-15 16:43:32.440616: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-15 16:43:32.452241: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
dt Prediction target recognized.
678 feature files found.
<_FlatMapDataset element_spec=TensorSpec(shape=(None, 1024), dtype=tf.float32, name=None)>
test_labels:
[[0 1 0]
 [0 0 1]
 [1 0 0]
 ...
 [0 0 1]
 [1 0 0]
 [0 0 1]]
Labels Shape: (678, 3)
678
[[1]
 [2]
 [0]
 [2]
 [1]
 [1]
 [1]
 [2]
 [0]
 [1]
 [2]
 [2]
 [0]
 [2]
 [0]
 [2]
 [1]
 [2]
 [2]
 [1]
 [2]
 [0]
 [0]
 

In [ ]:
# Manual decision tree according to trustee results
import os
import numpy as np

base_directory = '/content/drive/MyDrive/Colab Notebooks/first chunk'

total_files_count = 0
i = 0

for folder_name in ['GoogleDoc', 'GoogleDrive', 'Youtube']:
    folder_path = os.path.join(base_directory, folder_name)

    if os.path.isdir(folder_path):
        print(f"pass on : {folder_name}")
        files_count = len([f for f in os.listdir(folder_path) if f.endswith('.npy')])
        total_files_count += files_count

        for file_name in os.listdir(folder_path):
            if file_name.endswith('.npy'):
                file_path = os.path.join(folder_path, file_name)
                file_class = file_name.split('-')[0]

                array = np.load(file_path)
                #print(array.dtype, array.shape)

                if(array[31][4] <= 0.009):
                    if(array[30][0] <= 0.055):
                        if(array[22][0]<=0.234):
                            if(array[5][0]<=0.265): classes = "Youtube"
                            else: classes = "GoogleDoc"
                        else: classes = "GoogleDrive"
                    else:
                        if(array[29][4]<=0.016): classes = "GoogleDrive"
                        else: classes = "GoogleDoc"
                else: classes = "GoogleDoc"

                print(file_class, classes)
                if (file_class==classes):
                  i+=1


print(f"{i}/{total_files_count} is {i/total_files_count} accuracy")





pass on : GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDrive
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDoc
GoogleDoc GoogleDo